
server:
  port: 8080
spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/agency
    url: jdbc:mysql://localhost:3306/orm?useUnicode=true&serverTimezone=UTC
    username: root
    password: root
#    driver-class-name: org.postgresql.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/data/changelog/db.changelog-master.xml



